AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  LambdaZipS3Bucket:
    Description: ""
    Type: String
  LambdaZipS3Key:
    Description: ""
    Type: String

Outputs:
  HellowWorld:
    Value: !GetAtt HelloWorld.Value

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      Path: /
      Policies:
        - PolicyName: "root"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource:
                  - arn:aws:logs:*:*:*
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents


  HelloWorldFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "CustomResourceHelloWorld"
      Handler: handle
      Runtime: go1.x
      Timeout: 30
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref LambdaZipS3Bucket
        S3Key: !Ref LambdaZipS3Key

  HelloWorld:
    Type: Custom::HelloWorld
    Properties:
      ServiceToken: !GetAtt HelloWorldFunction.Arn
      Region: !Ref AWS::Region
